dist: trusty
sudo: false
language: php
php: 7.2

addons:
  sonarcloud:
    organization: "guillemcanal-github"

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - composer lint
  - composer test-ci

after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/phpunit.coverage.xml
  - sonar-scanner
