dist: trusty
sudo: false
language: php
php: 7.2

addons:
  sonarcloud:
    organization: "guillemcanal-github"

jobs:
  include:
  - stage: test
    install:
    - composer install
    before_install:
    - phpenv config-rm xdebug.ini
    script:
    - composer lint
    - composer test-ci
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f build/phpunit.coverage.xml
    - sonar-scanner

  - stage: docker-image:tagged
    if: tag IS present
    services:
    - docker
    script: bash ./scripts/docker-push.sh $TRAVIS_TAG

  - stage: docker-image:latest
    if: branch = master
    services:
    - docker
    script: bash ./scripts/docker-push.sh latest

